export const CUSTOMIZATION_NAME = {
    DATA__FILTER_SCHOOLS: 'DATA__FILTER_SCHOOLS',
    DATA__GET_SCHOOL: 'DATA__GET_SCHOOL',
    FILTERS__FILTER_CATEGORIES: 'FILTERS__FILTER_CATEGORIES',
    FILTERS__FILTER_DEFINITIONS: 'FILTERS__FILTER_DEFINITIONS',
    SCHOOL_PAGE_SECTIONS__SECTIONS: 'SCHOOL_PAGE_SECTIONS__SECTIONS',
    COMPONENTS__SCHOOL_CARD: 'COMPONENTS__SCHOOL_CARD',
    COMPONENTS__SCHOOL_HERO: 'COMPONENTS__SCHOOL_HERO',
} as const

export type CustomizationNameT =
    (typeof CUSTOMIZATION_NAME)[keyof typeof CUSTOMIZATION_NAME]
